name: Deploy to Hugging Face Spaces
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: SemdeGroot
          SPACE_NAME: Apotheek_Chatbot
        run: |
          git remote add space https://huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME || true
          git push --force https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main
